config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users' }
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :surfspots, only: %i[index show] do
    resources :favourites, only: %i[create destroy]
    patch "/change_fav_alert_pref", to: "favourites#change_fav_alert_pref"
  end

  resources :favourites do
    collection do
      get :my_feed
    end
  end

  resources :favourites, only: %i[index]
  resources :alerts, only: %i[index]

end

app/models/surfspot.rb
class Surfspot < ApplicationRecord
  has_many :favourites, dependent: :destroy
  has_many :posts, dependent: :destroy

  include PgSearch::Model
  pg_search_scope :super_search,
  against: [ :location , :name],
  using: {
    tsearch: { prefix: true }
  }
end

app/controllers/surfspots_controller.rb
class SurfspotsController < ApplicationController
  def index
    @surfspots = Surfspot.all
    if params[:query].present?
      @surfspots = Surfspot.super_search(params[:query])
    end
  end

  def show
    @user = current_user
    @surfspot = Surfspot.find(params[:id])
    @posts = @surfspot.posts
  end
end

app/views/surfspots/_surfspot.html.erb
<div class="card card-your-spots-home mt-3 mx-auto">
  <%= link_to surfspot_path(spot) do %>
    <img src="<%= spot.image_url %>" class="card-img-top custom-card-img" alt="<%= spot.name %>'s photo">
  <% end %>
  <%= link_to surfspot_path(spot) do %>
    <div class="card-body">
        <h5 class="card-title"><%= spot.name %></h5>
      <p class="card-text"><small class="text-body-secondary"><%= spot.location[0] %><%= spot.location[1..-1].downcase %></small></p>
    </div>
  <% end %>
</div>

app/views/surfspots/index.html.erb
<div class="container px-4">
<%= render "shared/searchform" %>
  <% @surfspots.each do |spot| %>
    <%= render 'surfspot', spot: spot %>
  <% end %>
</div>

app/views/surfspots/show.html.erb
<div class ="container">
  <%= render "shared/searchform" %>
  <div class="separator"></div>
  <div class="row">
    <div class="col-6">
      <div class="p-3"><h1><strong><%= @surfspot.name %></strong></h5>
      <h3 class="card-subtitle mb-2 text-body-secondary"><%= @surfspot.location %></h6>
      </div>
    </div>
    <div class="col-6 ">
      <div class="p-3 d-flex justify-content-end">
        <% if @user.favourites.where(surfspot_id: @surfspot).empty? %>
          <%= button_to 'Follow',
          surfspot_favourites_path(@surfspot),
          method: :post,
          class: 'button' %>
        <% else %>
          <%= button_to 'Following',
          surfspot_favourite_path(@surfspot),
          method: :delete,
          class: 'button-secondary' %>
        <% end %>

        <% if @user.favourites.where(surfspot_id: @surfspot).first %> <%# if its a favourite %>
          <% if @user.favourites.where(surfspot_id: @surfspot).first.alert == true %>
            <%= button_to surfspot_change_fav_alert_pref_path(@surfspot), method: :patch, class: 'button text-nowrap ms-1' do %>
            <i class="fa-solid fa-bell"></i> <small>ON</small>
            <% end %>
          <% else %>
            <%= button_to surfspot_change_fav_alert_pref_path(@surfspot), method: :patch, class: 'button-secondary text-nowrap ms-1' do %>
              <i class="fa-solid fa-bell"></i> <small>OFF</small>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="separator"></div>
    <div class="col-12 d-flex justify-content-center mx-auto p-2">
      <%= image_tag @surfspot.image_url, class: "img-fluid img-responsive" %>
     <%# <video width="320" height="240" controls> %>
        <%# <source src="https://surf-buddy-livestream-api-829506769985.europe-west1.run.app/livestream?spot_name=carcavelos&mode=stream" type="video/mp4"> %>
        <%# <source src="movie.ogg" type="video/ogg"> %>
        <%# Your browser does not support the video tag. %>
      <%# </video> %>


    </div>
  </div>
  <div class="row">
    <% if @surfspot.posts.empty?  %>
      <p class="pb-4 pt-3 text-center"><em>Sorry, no available Live Conditions at the moment...</em></p>
    <% else %>
      <h2 class="pb-4 pt-3 text-center">Live Conditions</h2>
      <% @surfspot.posts.reverse_each do |post|  %>
        <div class="col-12 col-lg-4">
          <%= render "posts/post", post: post %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>