config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users' }
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :surfspots, only: %i[index show] do
    resources :favourites, only: %i[create destroy]
    patch "/change_fav_alert_pref", to: "favourites#change_fav_alert_pref"
  end

  resources :favourites do
    collection do
      get :my_feed
    end
  end

  resources :favourites, only: %i[index]
  resources :alerts, only: %i[index]

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="d-flex flex-column align-items-center justify-content-around w-100 pt-5 pb-3 border-to bg-white" id="footer">
  <%= link_to image_tag("SurfBuddy_logo.png", class: "logo"), root_path %>
  <div class="py-3 d-flex flex-column align-items-center">
    <%= link_to "My spots", favourites_path, class: "footer-link" %>
    <%= link_to "Home", root_path, class: "footer-link" %>
  </div>
  <p><i class="fa-regular fa-copyright"></i> 2024, SurfBuddy, Inc.</p>
</footer>

app/views/shared/_level_assessement.html.erb
<div class="mb-3">
  <label for="form-select" class="form-label">How confident are you in catching waves on your own?</label>
  <select class="form-select" aria-label="Default select example">
  <option selected>Select one</option>
  <option value="1">I struggle to catch waves without assistance.</option>
  <option value="2">I can catch waves on my own but sometimes miss or mistime them.</option>
  <option value="3">I consistently catch waves on my own, even in challenging conditions.</option>
</select>
</div>
<div class="mb-3">
  <label for="form-select" class="form-label">What size of waves are you comfortable surfing?</label>
  <select class="form-select" aria-label="Default select example">
  <option selected>Select one</option>
  <option value="1">Small waves (1-3 feet).</option>
  <option value="2">Medium waves (3-6 feet).</option>
  <option value="3">Large waves (6+ feet).</option>
</select>
</div>
<div class="mb-3">
  <label for="form-select" class="form-label">How comfortable are you with performing turns and maneuvers on a wave?</label>
  <select class="form-select" aria-label="Default select example">
  <option selected>Select one</option>
  <option value="1">I'm still learning to stand and ride straight.</option>
  <option value="2">I can perform basic turns and maneuvers like cutbacks.</option>
  <option value="3">I can link advanced maneuvers like carves, cutbacks, and aerials.</option>
</select>
</div>
<div class="mb-3">
  <label for="form-select" class="form-label">What type of surfboard do you usually ride?</label>
  <select class="form-select" aria-label="Default select example">
  <option selected>Select one</option>
  <option value="1">Soft-top longboard or foam board.</option>
  <option value="2">Funboard or a shorter board with more maneuverability.</option>
  <option value="3">High-performance shortboard.</option>
</select>
</div><div class="mb-3">
  <label for="form-select" class="form-label">How familiar are you with reading the ocean conditions (e.g., wave direction, tides, wind)?</label>
  <select class="form-select" aria-label="Default select example">
  <option selected>Select one</option>
  <option value="1">I’m still learning how to read waves and conditions.</option>
  <option value="2">I can read waves and conditions well enough to position myself correctly.</option>
  <option value="3">I have a strong understanding of ocean conditions and can adapt to different environments.</option>
</select>
</div>

app/views/shared/_navbar.html.erb
<div class="d-flex align-items-center justify-content-between border z-3 py-3 px-1 sticky-top" id="navbar">
  <% if user_signed_in? %>
    <div class="d-flex align-items-center">
      <% if !current_user.photo.nil? %>
        <%= link_to root_path do %>
          <%= image_tag current_user.photo, class:"avatar"%>
        <% end %>
        <% end %>
      <div>
        <div class="mx-1" > Hi <%= current_user.first_name.capitalize %> 🏄🏻‍♂️ </div>
        <span class="level level-<%= current_user.surf_level.downcase %>"> <%= current_user.surf_level.capitalize %> </span>
      </div>
    </div>

    <div class="d-flex align-items-center">
      <div class="mx-4 my-2 p-1" id="dp-card" style="display: flex; align-items: center; justify-content: center;">
        <div class="position-relative">
          <%= link_to alerts_path, style:"cursor: pointer; font-size: 2em;" do %>
            <i class="fa-solid fa-bell" id="dp-bell"></i>
          <% end %>

          <% unless current_user.unread_alerts.zero? %>
            <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill border border-light bg-danger text-bg-secondary"><%= current_user.unread_alerts %> <span class="visually-hidden">unseen alerts</span></span>
          <% end %>

        </div>
      </div>



      <div class="nav-item dropdown">
        <div class="nav-link" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          <i class="fa-solid fa-water" style="padding: 10px; border-radius: 15px; font-size: 2em; display: flex; align-items: center; justify-content: center;" id="dp"></i>
        </div>
        <ul class="dropdown-menu">
          <li><%= link_to "My feed", my_feed_favourites_path, class: "dropdown-item" %></li>
          <li><%= link_to "Surfspots", surfspots_path, class: "dropdown-item" %></li>
          <li><%= link_to "My Spots", favourites_path, class: "dropdown-item" %></li>
          <li><hr class="dropdown-divider"></li>
          <li><%= link_to "Edit Profile", edit_user_registration_path, class: "dropdown-item" %></li>
          <li><%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: 'dropdown-item' %></li>
        </ul>
      </div>

    </div>
  <% else %>
    <div class="d-flex align-items-center justify-content-between w-100">
      <%= link_to root_path do %>
      <%= image_tag "SurfBuddy_logo.png" %>
      <% end %>
      <%= link_to "Sign in", new_user_session_path, class: "button" %>
    </div>
  <% end %>
</div>

app/views/shared/_searchform.html.erb
<%= form_with url: surfspots_path, method: :get, local: true, class: 'd-flex mt-4' do %>
  <%= button_tag(type: 'submit', class: 'btn') do %>
    <i class="fa-solid fa-magnifying-glass" style="font-size: 2em; color: #00808B;"></i>
  <% end %>
  <%= text_field_tag :query, params[:query], class:"form-control string required rounded-5",placeholder:'Search a spot' %>
<% end %>